### ISSUE TITLE
Eta in jacobian do/dh for non-delta refractive bsdf case

### ISSUE THREAD

**Issue by ommaury** [tizian/specular-manifold-sampling#3]
Hi Tizian,

For non-delta refractive bsdfs, when deriving the jacobian do/dh in the specular reflectance computation method (in the manifold_ss.pp and manifold_ms.cpp files), it seems you always use the bsdf raw eta, regardless of which side of the interface the ray comes from:

https://github.com/tizian/specular-manifold-sampling/blob/master/src/librender/manifold_ss.cpp#L647
https://github.com/tizian/specular-manifold-sampling/blob/master/src/librender/manifold_ms.cpp#L960

Shouldn't there be a test to invert eta if you're coming from the inside (as it is indeed the case for typical use cases)?

Thanks,
Olivier

**Comment by tizian** [comment]
Hi Olivier,
Good catch! Indeed that seems to be a small oversight. I'll push an update in a second.
Thanks for reporting it!
Best,
Tizian
